export const languagesSeed = [
  {
    code: "en",
    name: "English",
    nativeName: "English",
    flag: "🇬🇧",
    difficulty: 1,
    isActive: true,
  },
  {
    code: "fr",
    name: "French",
    nativeName: "Français",
    flag: "🇫🇷",
    difficulty: 2,
    isActive: true,
  },
  {
    code: "es",
    name: "Spanish",
    nativeName: "Español",
    flag: "🇪🇸",
    difficulty: 2,
    isActive: true,
  },
  {
    code: "de",
    name: "German",
    nativeName: "Deutsch",
    flag: "🇩🇪",
    difficulty: 3,
    isActive: true,
  },
  {
    code: "it",
    name: "Italian",
    nativeName: "Italiano",
    flag: "🇮🇹",
    difficulty: 2,
    isActive: true,
  },
  {
    code: "ja",
    name: "Japanese",
    nativeName: "日本語",
    flag: "🇯🇵",
    difficulty: 4,
    isActive: true,
  },
  {
    code: "zh",
    name: "Chinese (Mandarin)",
    nativeName: "中文",
    flag: "🇨🇳",
    difficulty: 5,
    isActive: true,
  },
  {
    code: "ru",
    name: "Russian",
    nativeName: "Русский",
    flag: "🇷🇺",
    difficulty: 4,
    isActive: true,
  },
];
