version: "3.8"

services:
  db-service:
    build:
      context: ..
      dockerfile: Dockerfile
      target: development
    container_name: penpal-ai-db-service
    volumes:
      - ../:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    command: npm run start:dev
    env_file:
      - ./db-service/.env
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - penpal-network
    healthcheck:
      test: [CMD, curl, -f, "http://localhost:3001/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  auth-service:
    build:
      context: ../../penpal-ai-auth-service
      dockerfile: Dockerfile
      target: development
    container_name: penpal-ai-auth-service
    volumes:
      - ../../penpal-ai-auth-service:/app
      - /app/node_modules
    ports:
      - "3002:3002"
    command: npm run start:dev
    env_file:
      - ./auth-service/.env
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - penpal-network
    healthcheck:
      test: [CMD, curl, -f, "http://localhost:3002/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongodb:
    image: mongo:6.0
    container_name: penpal-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
      - ./mongodb/init:/docker-entrypoint-initdb.d
    networks:
      - penpal-network
    environment:
      - MONGO_INITDB_DATABASE=penpal-ai
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_INITDB_USERNAME=penpal_user
      - MONGO_INITDB_PASSWORD=penpal_password
    command: [--auth, --bind_ip_all]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/admin -u admin -p admin123 --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  mongo-express:
    image: mongo-express:latest
    container_name: penpal-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin123
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_SITE_PORT=8081
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - penpal-network
    healthcheck:
      test: wget --quiet --tries=1 --spider http://admin:admin123@localhost:8081/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7.0-alpine
    container_name: penpal-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass redis123
    networks:
      - penpal-network
    healthcheck:
      test: [CMD, redis-cli, -a, redis123, ping]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

networks:
  penpal-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  redis_data:
    driver: local
